services:
  _defaults:
    autowire: true
    public: false

  OxidEsales\GraphQL\Base\Seo\Infrastructure\Factory\SeoEncoderArticleFactoryInterface:
    class: OxidEsales\GraphQL\Base\Seo\Infrastructure\Factory\SeoEncoderArticleFactory

  OxidEsales\GraphQL\Base\Seo\Infrastructure\Factory\SeoEncoderFactoryInterface:
    class: OxidEsales\GraphQL\Base\Seo\Infrastructure\Factory\SeoEncoderFactory
