# {{ $ids := "oe_graphql_base" }}ids: {{ $ids }}
# {{ $org := "oxid-esales" }}organisation: {{ $org }}
# {{ $name := "graphql-base" }}name: {{ $name }}
# {{ $repo := "OXID-eSales/graphql-base-module" }}repo: {{ $repo }}

install_shop_with_modules:
    cache:
        prepared_shop: false
    composer:
        transform: |
            {
                "require": {
                    "oxid-esales/oxideshop-ce": "{{ .Data.global.composer.dev_ref }}",
                    "oxid-esales/twig-component": "{{ .Data.global.composer.dev_ref }}",
                    "oxid-esales/twig-admin-theme": "{{ .Data.global.composer.dev_ref }}",
                    "oxid-esales/apex-theme": "{{ .Data.global.composer.dev_ref }}",
                    "oxid-esales/developer-tools": "{{ .Data.global.composer.dev_ref }}",
                    "{{ $org }}/{{ $name }}": "{{ .Data.global.composer.ref_name }}"
                },
                "repositories": {
                  "{{ $org }}/{{ $name }}": {
                    "type": "git",
                    "url": "https://github.com/{{ $repo }}.git"
                  }
                }
            }
    custom_script_container: |
        perl -pi -e 'print "SetEnvIf Authorization \"(.*)\" HTTP_AUTHORIZATION=\$1\n\n" if $. == 1' source/.htaccess
        vendor/bin/oe-console oe:database:reset --db-host=mysql --db-port=3306 --db-name=example --db-user=root --db-password=root --force
        vendor/bin/oe-console oe:module:activate "{{ $ids }}"
        vendor/bin/oe-console oe:theme:activate apex

runscript: &runscript
    matrix:
        script: |
            [
              "graphql_base:tests-unit",
              "graphql_base:tests-integration",
              "graphql_base:tests-codeception"
            ]
    graphql_base:
        path: 'vendor/{{ $org}}/{{ $name }}'

runslim:
    <<: *runscript
    matrix:
        script: |
            [
              "graphql_base:phpcs",
              "graphql_base:phpstan"
            ]

sonarcloud:
    matrix:
        testplan: '["-"]'
    strip_path: '/var/www/vendor/{{ print $org }}/{{ print $name}}/'
    project_key: 'OXID-eSales_graphql-base-module'
    project_name: '{{ $org}}/{{ $name }}'
    parameters: |
        -Dsonar.language=php
        -Dsonar.scm.provider=git
        -Dsonar.sources=src
        -Dsonar.tests=tests

finish:
    slack_title: '{{ print $name }} ({{ .Data.global.git.shop_ref }}) by {{ .Github.Actor }}'
