# {{ $ids := "oe_graphql_base" }}ids: {{ print $ids }}
# {{ $org := "oxid-esales" }}organisation: {{ print $org }}
# {{ $name := "graphql-base" }}name: {{ print $name }}
# {{ $order := "01" }}order: {{ print $order }}
prepare_shop:
  git:
    shop_ref: '{{ .Data.global.git.default_ref }}'

install_module:
  matrix:
      testplan: '["-"]'
  cache:
    prefix: &install_module_prefix 'moduleInstallation-ce-{{ .Github.SHA }}-{{ .Github.RunID }}'
  ids: &ids '{{ print $ids }}'
  activate: *ids
  git:
    module:
      url: &git_module_url '{{ .Github.Repository }}'
      ref: '{{ .Github.RefName }}'
  package_name: &package_name '{{ print $org }}/{{ print $name }}'
  path: *ids

phpunit:
  matrix:
    testplan: '["~/defaults/module_phpunit_unit.yml","~/defaults/module_phpunit_integration.yml"]'
  load_shop: *install_module_prefix

codeception:
    matrix:
        testplan: '["~/defaults/module_codeception_Acceptance_71x.yml"]'
    title: '{{ print $name }}-{{ print $order }}'
    load_shop: *install_module_prefix

runtest:
    matrix:
        testplan: 'skip'
    title: '{{ print $name }}-{{ print $order }}'
    load_shop: *install_module_prefix

sonarcloud:
    matrix:
        testplan: '["-"]'
    title: '{{ print $name }}-{{ print $order }}'
    project_key: 'OXID-eSales_graphql-base-module'
    project_name: *package_name
    parameters: |
        -Dsonar.language=php
        -Dsonar.scm.provider=git
        -Dsonar.sources=src
        -Dsonar.tests=tests

phpcs_tests:
  skip: true

styles:
    matrix:
        testplan: '["-"]'
    title: '{{ print $name }}-{{ print $order }}'
    load_shop: *install_module_prefix
    path: *ids
    module_ids: *ids

finish:
    slack_title: 'Module {{ print $name }} ({{ .Github.RefName }}) on {{ .Github.Repository }} by {{ .Github.Actor }}'
